AILocalHelper/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AILocalHelper.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

AILocalHelper/Pages/Index.cshtml.cs
using AILocalHelper.AI;
using AILocalHelper.DB;
using AILocalHelper.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AILocalHelper.Pages
{
    public class IndexModel : PageModel
    {
        private readonly LiteDBService _dBService;
        private readonly ChatService _chatService;
        private Settings _config;

        [BindProperty(SupportsGet = true)]
        public string PathToModel { get; set; }


        public IndexModel(
            LiteDBService dBService,
            ChatService chatService)
        {
            _dBService = dBService;
            _chatService = chatService;
            _config = _dBService.GetConfig();
        }

        public void OnGet()
        {
            PathToModel = _config.PathToModel;
        }

        public IActionResult OnPostSavePath()
        {
            _dBService.SetPathToModel(PathToModel);

            return RedirectToPage();
        }

        public IActionResult OnPostResetConfig()
        {
            _dBService.ResetConfig();

            return RedirectToPage();
        }

        public IActionResult OnPostCleanContext()
        {
            _dBService.ClearContext();

            return RedirectToPage();
        }
    }
}

AILocalHelper/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/5.0.11/signalr.min.js"></script>

<style>
    .history-record {
        padding: 10px;
        margin: 5px 0;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #f9f9f9;
    }

    .history-record:hover {
        background-color: #f1f1f1;
    }

    #AIResponse {
        display: none;
        white-space: pre-wrap; 
    }
</style>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <form method="post" asp-page-handler="SavePath">
        <input style="width:90%" type="text" name="PathToModel" value="@Model.PathToModel" />
        <button type="submit">Save path to model</button>
    </form>

    <br />
    <form method="post" asp-page-handler="CleanContext">
        <button type="submit">Clean Context</button>
    </form>

    <form method="post" asp-page-handler="ResetConfig">
        <button id="reset" type="submit">Reset config</button>
    </form>
    <br />

    <form method="post" id="AskForm">
        <input type="text" style="width:80%" id="UserPrompt" />
        <button type="submit">Ask</button>
    </form>
    <br />

    <div id="AIResponse" class="history-record"></div>
    <div id="HistoryRecords"></div>
</div>

<script>
    const thinkingText = "Thinking ....";
    var allowedToTypeAINext = true;

    const connection = new signalR.HubConnectionBuilder()
        .withUrl("/communicationHub")
        .build();

    const typeWriterEffect = (element, text, speed = 70) => {
        if (!allowedToTypeAINext) return;

        allowedToTypeAINext = false;

        let i = 0;
        const interval = setInterval(() => {
            if (i < text.length) {
                element.innerHTML += text.charAt(i);
                i++;
            } else {
                clearInterval(interval);
                allowedToTypeAINext = true;
            }
        }, speed);
    };

    const updateAIResponseField = (message) => {
        const aiResponseElement = document.getElementById("AIResponse");
        if (!message) {
            aiResponseElement.innerText = "";
            aiResponseElement.style.display = "none";
        } else {
            if (aiResponseElement.innerText == thinkingText){
                aiResponseElement.innerText = "";
            }
            aiResponseElement.style.display = "block";
            
            const currentLength = aiResponseElement.innerHTML.length;

            const newPart = message.slice(currentLength);
            typeWriterEffect(aiResponseElement, newPart);
        }
    };

    const updateHistoryField = (message) => {
        const historyRecordsContainer = document.getElementById("HistoryRecords");
        const recordDiv = document.createElement("div");
        recordDiv.className = "history-record";
        recordDiv.innerText = message;
        historyRecordsContainer.prepend(recordDiv);
    };

    connection.on("SetPartialAIResponse", (message) => {
        updateAIResponseField(message);
    });

    connection.on("AddHistoryRecord", (message) => {
        updateHistoryField(message);
    });

    connection.on("SetLock", (isLocked) => {
        const buttons = document.querySelectorAll('form button');
        buttons.forEach(button => {
            button.disabled = button.id == "reset" ? false : isLocked;
        });

        if (!isLocked) {
            updateAIResponseField("");
        }
    });

    connection.start().then(() => {
        document.getElementById("AskForm").addEventListener("submit", function (event) {
            event.preventDefault();
            const userPrompt = document.getElementById("UserPrompt").value;
            if (userPrompt) {
                updateAIResponseField("Thinking ....");
                connection.invoke("AskAI", userPrompt).catch(err => console.error(err.toString()));
                document.getElementById("UserPrompt").value = "";
            }
        });

        connection.invoke("GetHistoryRecords").then(historyRecords => {
            console.log(historyRecords);

            historyRecords.forEach(record => {
                updateHistoryField(record);
            });
        }).catch(err => console.error(err.toString()));
    }).catch(err => console.error(err.toString()));
</script>

AILocalHelper/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AILocalHelper</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AILocalHelper.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                AILocalHelper
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AILocalHelper
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>